// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pjkmeaeoqoqmnyozlzap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_YkI2b-cEjKrx2vTFobzx6Q_VtmNRXe1";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
